# Search Indexing Chunking Configuration
# Optimized for search engine indexing and full-text search

profile_name: "search_indexing"
description: "Configuration optimized for search indexing with balanced chunk sizes"

# Strategy selection and fallbacks
strategies:
  primary: "sentence_based"
  fallbacks:
    - "fixed_size"
    - "word_based"
    - "paragraph_based"

  # Strategy-specific configurations
  configs:
    sentence_based:
      max_sentences: 6
      min_sentences: 2
      max_chunk_size: 1000
      overlap_sentences: 1
      sentence_splitter: "simple"

    fixed_size:
      chunk_size: 512
      overlap_size: 50
      unit: "character"
      preserve_boundaries: true

    word_based:
      max_words: 150
      min_words: 50
      overlap_words: 10
      preserve_sentences: true

    paragraph_based:
      max_paragraphs: 2
      max_chunk_size: 800
      preserve_structure: false

# Strategy selection rules optimized for search
strategy_selection:
  web_page:
    primary: "sentence_based"
    fallbacks: ["fixed_size", "word_based"]

  documentation:
    primary: "section_based"
    fallbacks: ["sentence_based", "fixed_size"]

  faq:
    primary: "qa_based"
    fallbacks: ["sentence_based", "paragraph_based"]

  product_description:
    primary: "feature_based"
    fallbacks: ["sentence_based", "fixed_size"]

# Preprocessing configuration for search optimization
preprocessing:
  enabled: true
  normalize_whitespace: true
  remove_headers_footers: false  # Keep for context
  clean_markup: true
  normalize_unicode: true

  # Search-specific preprocessing
  lowercase_content: false  # Preserve case for proper nouns
  remove_stop_words: false  # Keep for natural language queries
  extract_keywords: true

  custom_steps:
    - normalize_urls
    - extract_metadata
    - preserve_anchors

# Postprocessing configuration for search
postprocessing:
  enabled: true
  remove_empty_chunks: true
  merge_short_chunks: true
  min_chunk_size: 100
  max_merge_size: 800
  deduplicate: true
  similarity_threshold: 0.95  # High threshold for search

  # Search-specific postprocessing
  add_search_metadata: true
  extract_entities: false
  calculate_readability: true
  add_language_tags: true

  # Quality enhancement
  enhance_metadata: true
  normalize_content: true
  add_content_hash: true

# Quality thresholds for search indexing
quality_thresholds:
  min_coherence: 0.4  # Lower threshold for diverse content
  min_coverage: 0.95  # High coverage important for search
  max_overlap_ratio: 0.2  # Allow some overlap for context
  min_information_density: 0.2

# Performance settings for large-scale indexing
performance:
  streaming_threshold: 1048576  # 1MB - lower threshold for faster processing
  parallel_processing: true
  memory_limit: 536870912  # 512MB - efficient for batch processing
  timeout: 120  # 2 minutes
  batch_size: 100  # Process in batches

# Output preferences for search systems
output:
  include_metadata: true
  include_quality_scores: false
  chunk_id_format: "idx_{source_hash}_{index:06d}"
  preserve_source_structure: false
  include_search_hints: true

  # Search-specific output
  include_content_type: true
  include_language: true
  include_readability_score: true
  add_indexing_timestamp: true

# Search-specific settings
search_optimization:
  # Chunk size optimization for different content types
  content_type_sizes:
    title: 100
    heading: 200
    paragraph: 500
    list_item: 150
    code_block: 300

  # Keyword density thresholds
  keyword_density:
    min_density: 0.01
    max_density: 0.05

  # Content scoring
  content_scoring:
    title_weight: 3.0
    heading_weight: 2.0
    first_paragraph_weight: 1.5
    link_text_weight: 1.2
